name: 'Badges'
description: 'Set badges in readme file'
inputs:
  cypress_outcome:
    description: 'Cypress outcome'
    required: true
runs:
  using: "composite"
  steps:
    - run: python ${{ github.action_path }}/badges.py ${{ inputs.cypress_outcome }}
      shell: bash
