name: Actions
on: [push]
jobs:
  Linter_job:
    name: Linter job
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install your linters here
      - name: Run linters
        run: npm install && npm run lint

  Cypress_job:
    name: Cypress job
    runs-on: ubuntu-latest
    needs: Linter_job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        id: cypress
        continue-on-error: true
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
      
      - name: Outcome
        run: |
            echo ${{ steps.cypress.outcome }} > result.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-result
          path: result.txt

  Add_badge_job:
    name: Add badge job
    runs-on: ubuntu-latest
    needs: Cypress_job
    if: ${{ always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: cypress-result

      - name: Cypress output
        id: cypress-output
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"

      - uses: ./.github/actions/badges/
        with:
          cypress_outcome: ${{ steps.cypress-output.outputs.cypress_outcome }}

      - name: Commit
        run: |
          git config user.email "badgebot@github.com"
          git config user.name "badgebot"
          git add .
          git commit --allow-empty -m "Badges"
          git remote set-url origin https://iferrer20:${{ secrets.GITHUB_TOKEN }}@github.com/iferrer20/ghActions-Practica.git
          git push

  Deploy_job:
    name: Deploy job
    runs-on: ubuntu-latest
    needs: Cypress_job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vercel deployment
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}


  Notification_job:
    name: Notification job
    runs-on: ubuntu-latest
    needs: [Deploy_job, Cypress_job, Linter_job, Add_badge_job]
    if: ${{ always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send email
        uses: ./.github/actions/email/
        with: 
          text: |
            Se ha realizado un push en la rama main que ha provocado la ejecución del
            workflow nombre_repositorio_workflow con los siguientes resultados
            Linter: ${{ needs.Linter_job.result }}<br>Cypress: ${{ needs.Cypress_job.result }}<br>Badges: ${{ needs.Add_badge_job.result }}<br>${{ needs.Deploy_job.result }}

          from_email: ${{ github.event.pusher.email }}
          to_email: ${{ github.event.pusher.email }}
          name: ${{ github.event.pusher.name }}
          subject: | 
            Re: ${{ github.event.head_commit.message }} Resultado del workflow ejecutado
          mailjet_api_key: ${{ secrets.MAILJET_API_KEY }}
          mailjet_secret_key: ${{ secrets.MAILJET_SECRET_KEY }}
